# -*- coding: utf-8 -*-
"""Ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/173Ld9jsX3Ukv4L-0Hdox91e6vM8U8e8C
"""



a=10
b=20
c=a+b
print(c)

"""Addition of given two Number"""

